### ISSUE TITLE
clang-tags won't build (Debian jessie, libclang-3.4-dev and libclang-3.5-dev installed)

### ISSUE THREAD

**Issue by nrnrnr** [ffevotte/clang-tags#20]
I'm following the instructions at http://ffevotte.github.io/clang-tags/install.html when I trip over the following error:

```
: nr@labrador 67171 ; cmake ../src                   
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find Libclang (missing: Libclang_LIBRARY Libclang_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLibclang.cmake:13 (find_package_handle_standard_args)
  CMakeLists.txt:34 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/nr/net/clang-tags/build/CMakeFiles/CMakeOutput.log".
: nr@labrador 67172 ; less -N /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake        
: nr@labrador 67173 ; less cmake/Modules/FindLibclang.cmake   
cmake/Modules/FindLibclang.cmake: No such file or directory
: nr@labrador 67174 ; less ../src/cmake/Modules/FindLibclang.cmake
: nr@labrador 67175 ; wd
~/net/clang-tags/build 
: nr@labrador 67176 ; cd ..
: nr@labrador 67177 ; rm -rf build
: nr@labrador 67178 ; md build
: nr@labrador 67179 ; cd build
: nr@labrador 67180 ; cmake ../src
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found LibJsoncpp: /usr/lib/libjsoncpp.so  
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find Libclang (missing: Libclang_LIBRARY Libclang_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLibclang.cmake:13 (find_package_handle_standard_args)
  CMakeLists.txt:34 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/nr/net/clang-tags/build/CMakeFiles/CMakeOutput.log".
```

Investigation reveals that the build script seems to be looking for clang 3.2.
I have clang 3.4 and clang 3.5 installed (which is what's on offer from Debian jessie):

```
: nr@labrador 67181 ; cat -n ../src/cmake/Modules/FindLibclang.cmake           
     1  find_path (Libclang_INCLUDE_DIR clang-c/Index.h
     2    HINTS "${LIBCLANG_ROOT}/include"
     3    PATH  "/usr/lib/llvm-3.2/include")
     4
     5  find_library (Libclang_LIBRARY clang
     6    HINTS "${LIBCLANG_ROOT}/lib"
     7    PATH  "/usr/lib/llvm-3.2/lib")
     8
     9  set (Libclang_LIBRARIES    ${Libclang_LIBRARY})
    10  set (Libclang_INCLUDE_DIRS ${Libclang_INCLUDE_DIR})
    11
    12  include (FindPackageHandleStandardArgs)
    13  find_package_handle_standard_args (Libclang  DEFAULT_MSG
    14    Libclang_LIBRARY Libclang_INCLUDE_DIR)
    15
    16  mark_as_advanced (Libclang_INCLUDE_DIR Libclang_LIBRARY)
```

I understand nothing of cmake or libclang, so not sure if blithely changing to `/usr/lib/llvm-3.5` is really desirable here.

**Comment by ffevotte** [comment]
Hi,

you're right: `FindLibclang.cmake` looks for an outdated version of libclang (which was current when I wrote it). You can safely modify the path to match your system version.

Alternatively, the standard way of telling `cmake` where to find missing dependencies is through  `-D` command-line switches. For example:

```
cmake ../src -D LIBCLANG_ROOT=/usr/lib/llvm-3.5
```

Although I've never tested building `clang-tags` with recent versions of `libclang`, it should work (provided that the API did not change since then).

Does it help ?

**Comment by nrnrnr** [comment]
Works like a charm and passes its regression tests.  One file triggers a couple of compiler warnings.

I don't know if it's possible to tell CMake to try multiple paths for llvm, but looking for any of versions 3.2, 3.3, 3.4, 3.5 might be good.

**Comment by nrnrnr** [comment]
FYI, I had a little bit of trouble discovering the `clang-tags load` command, because it is mentioned only very peripherally in the user manual---although it is prominently in place in the quick-start guide.

However, I did get things to work, and from what I see, as soon as I understand the database schema, it should be possible to extract everything I might want from the sqlite data base.  Thank you for your help, and for a valuable tool!

**Comment by ffevotte** [comment]
Thanks for the feedback.

As you might have noticed, I haven't been able to work much on `clang-tags` recently. But feedbacks like yours motivate me to try and find some time to make the project live again.

**Comment by nrnrnr** [comment]
It's a great project!  It's going to take me some time to integrate it into my ecosystem, so I don't expect it to happen soon, but when it does, I will let you know.
