### ISSUE TITLE
List of all defined symbols?

### ISSUE THREAD

**Issue by nrnrnr** [ffevotte/clang-tags#21]
Is there a way to get a list of all defined symbols?  If I could do that, I could dump the entire index to find out what is there?  Or maybe I should try to discover the format of the configuration file used by the Emacs mode?

The problem I am trying to solve is to incorporate my source code into a LaTeX document and to include a link from each use of each identifier to the place in the LaTeX document where that identifier is defined.   I have the information linking C source code locations to the LaTeX document, and I am hoping to integrate that with the cross-reference information from clang-tags.

**Comment by ffevotte** [comment]
I'm not sure I understand your question...

Once you have the C source code location, you can find the definition of the symbol at point using something like

```
clang-tags find-def -i ../src/main.cxx 942
```

Then you'll have to parse an output similar to:

```
-- display -- MemberRefExpr display
   ../src/main.cxx:21-23:8-3: display
   c:@S@MyClass>#I@F@display#

-- b.display() -- CallExpr display
   ../src/main.cxx:21-23:8-3: display
   c:@S@MyClass>#I@F@display#

-- main () { int display = 3; //(ref:displ... -- FunctionDecl main
   ../src/main.cxx:26-34:5-1: main
   c:@F@main
```

The definition you want is generally the first one.

Does it answer the question? Or have I missed something?

**Comment by nrnrnr** [comment]
It looks like this one can be solved by interrogating the `tags` table of the clang-tags sqlite database, which is stored in `.ct.sqlite` in the compilation directory.
